app/_includes/blogpost.html
Closes raumzeitlabor/rzl-homepage#32.
=> German date formatting in blog posts

app/_posts/2014-09-23-sticken-leicht-gemacht-workshop-fur-kinder.html
Fixes raumzeitlabor/rzl-homepage#50
=> Reformat post to fix layout issues

app/kontakt/anfahrt/index.html, app/scripts/anfahrt.js
Add map overlays showing the paths described in the text.
While here make the way from the two different gates to the RaumZeitLabor two
different steps.
Closes raumzeitlabor/rzl-homepage#18
=> Add map overlays

app/kontakt/anfahrt/index.html, app/scripts/anfahrt.js
* If the main gate is closed, don't guide the visitor to the back gate
immediately, let him call the RZL to open the gate first.
* Spread the phone number so it is always available when needed.
=> Rework navigation

app/_posts/2015-02-19-exkursion-zum-grosskraftwerk-mannheim-gkm.md
* fix metadata
* add birthdate to needed information
=> Blogpost: Update GKM Exkursion

app/_includes/blogpost.html, app/_layouts/default.html
This prevents the webserver from sending a 301 to the trailing-slashed location.
=> Update navigation links: add trailing slash

app/scripts/anfahrt.js
Handy to display the address of RaumZeitLabor on map.
=> Add popups to interactive map

app/_layouts/default.html
Überlegungen:
* Die Satzung dürfte die wenigsten Besucher*innen unserer Homepage interessieren. Zumindest aber weniger als Mitgliedschaft, Beitragsordnung und Spendenmöglichkeiten.
* Das Wiki ist ein externer Link, ich finde es daher wesentlich intuitiver den ans Ende zu stellen. Außerdem glaube ich auch hier dass es für Menschen die sich nur kurz über uns informieren wollen weniger von Interesse ist als die anderen Seiten.
=> Menü-Umsortierung

Gruntfile.js, app/_plugins/rss_url_filter.rb, app/feed.xml
=> Absolutify relative links in RSS feeds

app/scripts/tumblr.js
Correct racy code segments and use more tolerant targeted height
resizing.
closes #5, #35
=> Fix gallery rendering

app/scripts/tumblr.js
[see plenum protocol](https://wiki.raumzeitlabor.de/wiki/20150705_-_Plenum#Ponys.2C_Au.C3.9Fenwirkungs.2C_Zensur.2C_Adminterror.2C_ZOMG.21.21.21)
=> Remove image filter

app/_posts/2015-08-09-bericht-stick-we-2.md
=> Replace image in blogpost "Bericht Stick-WE #2"

_config.yml, app/_includes/blogpost.html
This should close #202 
I've added a link tag around the avatar image and name in the Blog which links to the Wiki Userpage of each author.
This pull-request is done so that I can test it. DO NOT merge yet...
=> Tabascoeye avatar links

app/_layouts/default.html
Reverts raumzeitlabor/rzl-homepage#204
=> Revert 593b3d34056f32c252a7fa3eda7c29e8eed78dd4

package.json
should fix https://github.com/gruntjs/grunt-contrib-imagemin/issues/208
=> Update imagemin to 1.0.0

.travis.yml, deploy.sh
It looks like Travis disabled IPv6 connectivity on vm-based boxes.
=> Deploy via IPv4

app/impressum/index.html
=> Update the impressum

app/_posts/2016-12-10-exkursion-zum-rnv.md, app/_posts/2016-12-31-hackerspace-xmas-challenge.md, app/_posts/2017-02-07-hackertour-holzheizkraftwerk.md
* Neuer blogpost Exkursion Heizkraftwerk
* zwei vorbereitete Posts für RNV und XMAS Challenge (to be filled)
=> Alte berichte + neuer post

app/_layouts/default.html
noch ein Link über den sich Amazon beschwert hat entfernt
=> removed second amazon link

app/scripts/youtube.js
Use the enhanced privacy mode also on the "Videos" page.
=> Use the enhanced privacy mode for embedded Youtube videos

app/_layouts/default.html, app/verein/spenden/index.html
Ich glaube Flattr hat irgendwann aufgehört, einzelne Spenden anzunehmen. So oder so ist der Link aktuell ein 404.
=> Remove defunct flattr link

app/_posts/2019-01-03-Waffelfest.md
new blog post, invitation to the Waffelfest
=> created Waffelfest

app/scripts/events.js, app/styles/main.css
Please do not merge yet. Only a test-PR to have the preview build.
=> mark an event that is "today" with different color in calendar

Gemfile, _config.yml, app/_includes/blogpost.html, app/_layouts/default.html, app/blog/index.html
Update jekyll to 3.8.5 and install jekyll-paginate-v2.
Solves #332
=> Update jekyll to 3.8.5

app/verein/mitgliedschaft/index.html
Mitgliedsbeitrag auf der Mitgliedschafts-Seite ist seit der MV am 21.08.2018 nicht mehr aktuell. Auf der Beitragsordnungs-Seite wurde das schon angepasst.
=> Adjust membership fee on "Mitgliedschaft" page

app/_posts/2020-03-14-covid19.md, app/events/index.html
first attempt of removing the calendar without deleting all events manually
=> trying to remove the calendar for now

app/_posts/2020-07-01-will-hack-for-space.md, app/index.html
* changed start page to include current situation
* new blog post with our requirements for new rooms
=> Endeanfang

app/scripts/events.js
on first call of the webpage, only upcoming events shall be shown,
when changing the month "prev/next" and even when coming back to the current month, ALL events shall be shown
=> WIP: trying simple way of only showing upcoming events

app/index.html, app/kontakt/anfahrt/index.html
Links zur Hygienekonzept WIkiseite, damit das hoffentlich mal allen ins Gesicht leuchtet *seufz*
(index seite, sowie "anfahrt")
=> Hygiene links

app/kontakt/mailingliste/index.html
The direct POST no longer works because it requires CSRF, so I just give up and include the link to the mailman instead
=> remove direct subscribe form

.github/workflows/deploy.sh, .github/workflows/deploy.yml
Some suggestions from IRC/Matrix for better error handling on deploy.
=> better deploy error handling

.github/workflows/deploy.sh, .github/workflows/deploy.yml
its easier to test and less confusing that way
=> move the error handling back to deploy.sh

_config.yml, app/blog/index.html
=> trying to repair pagination

app/kontakt/mailingliste/index.html
because the postorious is broken, we need to tell people to use the "*-join" email address instead
=> use direct subscribe link for ML

app/bilder/index.html, app/index.html
=> add link to 360° Rundgang

app/kontakt/mailingliste/index.html
=> re-add the link to mailman
